name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies (Windows)
      if: runner.os == 'Windows'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt pyinstaller

    - name: Install dependencies (Linux/macOS)
      if: runner.os != 'Windows'
      run: |
        python -m pip install --upgrade pip
        pip install PyQt6==6.9.1 keyboard==0.13.5 monitorcontrol==4.1.1 Pillow==11.0.0 screeninfo==0.8.1 pyinstaller

    - name: Build Windows executable
      if: runner.os == 'Windows'
      run: |
        pyinstaller --onefile --windowed --icon=myicon.ico --add-data "myicon.ico;." --noupx -n MonitorNap-Windows --distpath dist --workpath build monitornap.py

    - name: Build Linux executable
      if: runner.os == 'Linux'
      run: |
        pyinstaller --onefile --windowed --add-data "myicon.ico:." --noupx -n MonitorNap-Linux --distpath dist --workpath build monitornap.py

    - name: Build macOS executable
      if: runner.os == 'macOS'
      run: |
        pyinstaller --onefile --windowed --add-data "myicon.ico:." --noupx -n MonitorNap-macOS --distpath dist --workpath build monitornap.py

    - name: Package macOS app as zip
      if: runner.os == 'macOS'
      run: |
        cd dist
        zip -r MonitorNap-macOS.app.zip MonitorNap-macOS.app
        rm -rf MonitorNap-macOS.app

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: monitornap-${{ runner.os }}
        path: dist/*

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Display structure of downloaded files
      run: ls -R artifacts

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: artifacts/**/*
        tag_name: ${{ github.ref_name }}
        name: MonitorNap ${{ github.ref_name }}
        body: |
          ## MonitorNap ${{ github.ref_name }}

          Download the appropriate version for your platform:
          - **Windows**: `MonitorNap-Windows.exe` - Download and run
          - **Linux**: `MonitorNap-Linux` - Download, make executable with `chmod +x MonitorNap-Linux`, then run
          - **macOS**: `MonitorNap-macOS.app.zip` - Download, extract, and run the .app

          See the [README](https://github.com/${{ github.repository }}) for installation and usage instructions.
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
